### ISSUE TITLE
SOE needs migrated to ArcGIS Enterprise SDK for use with ArcGIS Pro runtime services (10.9+)

### ISSUE THREAD

**Issue by mayja02** [nicogis/DS-Utility-SOE#1]
Domenico, 

Reaching out to see if there is a plan to migrate this SOE to the ArcGIS Enterprise SDK so it can be implemented on ArcGIS services published using the ArcGIS Pro runtime to ArcGIS Enterprise 10.9+

This is a fantastic utility and my org. has struggled in our attempts to migrate to the Enterprise SDK. This migration is becoming more urgent as Enterprise 10.9.1 is the last version of ArcGIS Enterprise that will support ArcMap runtime services.

**Comment by nicogis** [comment]
[mayja02](https://github.com/mayja02) Actually the problem is that Location library is not available in Enterprise SDK but only available in ArcObjects SDK, so it’s not possible to create a RouteMeasureLocator in Enterprise SDK . I hope that Esri exposes them in Enterprise SDK

**Comment by nicogis** [comment]
News: Esri has added this library in sdk in list of request of enhancement
